name: drift-env
channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.3
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - matplotlib>=3.0.0
  - pandas>=1.0.0
  - pyyaml>=5.1
  - gym>=0.17.2
  - tensorboard>=1.14.0
  - icecream=2.1.3
  - pip:
    - torchdiffeq>=0.2.3
    - tensorboardX>=1.6.0
    - ray>=1.1.0
    - setproctitle>=1.2.2
    - psutil>=5.8.0
    - tqdm>=4.62.0